default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: Chat_development
  username: root
  password: 
  host: 127.0.0.1
  port: 3306

development:
  <<: *default

production:
  adapter: postgresql
  encoding: unicode
  database: Chat_production
  username: KDRaypole01
  password: test
